-- ============================================================
-- Password Fix Script
-- Run this in phpMyAdmin if users cannot log in.
-- Sets all demo accounts to password: Admin@1234
-- Hash generated by PHP password_hash('Admin@1234', PASSWORD_DEFAULT)
-- ============================================================

USE `nhis_pregnancy`;

UPDATE `users` SET `password` = '$2y$10$9IXzQDCfIsb1ROJu.HEzMOlvr.N.25LtOe0b.MFoLCzSIzKq6JVRu'
WHERE `username` IN ('admin', 'abena.mensah', 'kofi.agyemang');
