-- ============================================================
-- NHIS Pregnancy Exemption Registration and Records Management System
-- Twifo Praso, Central Region, Ghana
-- Database: nhis_pregnancy
-- Version: 1.0
-- ============================================================

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

-- ------------------------------------------------------------
-- Create and select database
-- ------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS `nhis_pregnancy` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `nhis_pregnancy`;

-- ============================================================
-- TABLE: roles
-- ============================================================
CREATE TABLE IF NOT EXISTS `roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_role_name` (`role_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `roles` (`id`, `role_name`, `description`) VALUES
(1, 'Administrator', 'Full system access including user management, reports, settings and audit logs'),
(2, 'Staff', 'Data entry and records management access for pregnancy registrations');

-- ============================================================
-- TABLE: users
-- ============================================================
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(150) NOT NULL,
  `username` VARCHAR(80) NOT NULL,
  `email` VARCHAR(150) DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role_id` INT(11) NOT NULL DEFAULT 2,
  `phone` VARCHAR(20) DEFAULT NULL,
  `status` ENUM('active','inactive') NOT NULL DEFAULT 'active',
  `must_change_password` TINYINT(1) NOT NULL DEFAULT 0,
  `last_login` DATETIME DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_username` (`username`),
  KEY `fk_users_role` (`role_id`),
  CONSTRAINT `fk_users_role` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Default admin account
-- Username: admin  |  Password: Admin@1234  (CHANGE AFTER FIRST LOGIN)
-- Hash generated by PHP password_hash('Admin@1234', PASSWORD_DEFAULT)
INSERT INTO `users` (`id`, `full_name`, `username`, `email`, `password`, `role_id`, `phone`, `status`, `must_change_password`) VALUES
(1, 'System Administrator', 'admin', 'admin@nhis-twifopraso.gov.gh',
 '$2y$10$9IXzQDCfIsb1ROJu.HEzMOlvr.N.25LtOe0b.MFoLCzSIzKq6JVRu', 1, '0200000000', 'active', 1),
(2, 'Abena Mensah', 'abena.mensah', 'abena@nhis-twifopraso.gov.gh',
 '$2y$10$9IXzQDCfIsb1ROJu.HEzMOlvr.N.25LtOe0b.MFoLCzSIzKq6JVRu', 2, '0244123456', 'active', 0),
(3, 'Kofi Agyemang', 'kofi.agyemang', 'kofi@nhis-twifopraso.gov.gh',
 '$2y$10$9IXzQDCfIsb1ROJu.HEzMOlvr.N.25LtOe0b.MFoLCzSIzKq6JVRu', 2, '0201234567', 'active', 0);

-- ============================================================
-- TABLE: communities
-- ============================================================
CREATE TABLE IF NOT EXISTS `communities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `community_name` VARCHAR(150) NOT NULL,
  `district` VARCHAR(100) DEFAULT 'Twifo Atti-Morkwa',
  `region` VARCHAR(100) DEFAULT 'Central Region',
  `status` ENUM('active','inactive') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_community_name` (`community_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `communities` (`community_name`, `district`, `region`) VALUES
('Twifo Praso', 'Twifo Atti-Morkwa', 'Central Region'),
('Twifo Hemang', 'Twifo Atti-Morkwa', 'Central Region'),
('Twifo Morkwa', 'Twifo Atti-Morkwa', 'Central Region'),
('Nkwabeng', 'Twifo Atti-Morkwa', 'Central Region'),
('Assin Fosu', 'Assin Central', 'Central Region'),
('Breman Asikuma', 'Breman Asikuma', 'Central Region'),
('Eshiem', 'Twifo Atti-Morkwa', 'Central Region'),
('Krofu', 'Twifo Atti-Morkwa', 'Central Region'),
('Ohiamakrom', 'Twifo Atti-Morkwa', 'Central Region'),
('Adiembra', 'Twifo Atti-Morkwa', 'Central Region'),
('Other', 'Other', 'Other');

-- ============================================================
-- TABLE: health_facilities
-- ============================================================
CREATE TABLE IF NOT EXISTS `health_facilities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `facility_name` VARCHAR(200) NOT NULL,
  `facility_type` VARCHAR(100) DEFAULT NULL,
  `location` VARCHAR(150) DEFAULT NULL,
  `status` ENUM('active','inactive') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_facility_name` (`facility_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `health_facilities` (`facility_name`, `facility_type`, `location`) VALUES
('Twifo Praso Government Hospital', 'Hospital', 'Twifo Praso'),
('Twifo Praso Health Centre', 'Health Centre', 'Twifo Praso'),
('Hemang CHPS Compound', 'CHPS', 'Twifo Hemang'),
('Morkwa Health Centre', 'Health Centre', 'Twifo Morkwa'),
('Nkwabeng CHPS Compound', 'CHPS', 'Nkwabeng'),
('Eshiem CHPS Compound', 'CHPS', 'Eshiem'),
('Krofu Health Post', 'Health Post', 'Krofu'),
('Other Facility', 'Other', 'Other');

-- ============================================================
-- TABLE: pregnant_women (core records table)
-- ============================================================
CREATE TABLE IF NOT EXISTS `pregnant_women` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `record_number` VARCHAR(30) NOT NULL COMMENT 'System-generated unique record number e.g. NHIS-TP-2024-00001',
  `nhis_membership_number` VARCHAR(20) DEFAULT NULL COMMENT '8-digit NHIS membership number',
  `ghana_card_number` VARCHAR(20) DEFAULT NULL COMMENT 'Ghana Card Number: GHA-XXXXXXXXX-X',
  `first_name`  VARCHAR(80)  NOT NULL,
  `middle_name` VARCHAR(80)  DEFAULT NULL,
  `last_name`   VARCHAR(80)  NOT NULL,
  `full_name`   VARCHAR(150) GENERATED ALWAYS AS (TRIM(CONCAT_WS(' ', `first_name`, NULLIF(`middle_name`,''), `last_name`))) STORED COMMENT 'Auto-computed from first/middle/last name',
  `date_of_birth` DATE DEFAULT NULL,
  `sex` ENUM('Female') NOT NULL DEFAULT 'Female',
  `phone` VARCHAR(20) DEFAULT NULL,
  `alt_phone` VARCHAR(20) DEFAULT NULL,
  `community_id` INT(11) DEFAULT NULL,
  `community_other` VARCHAR(150) DEFAULT NULL COMMENT 'If community not in list',
  `district` VARCHAR(100) DEFAULT 'Twifo Atti-Morkwa',
  `region` VARCHAR(100) DEFAULT 'Central Region',
  -- Pregnancy Information
  `registration_date` DATE NOT NULL COMMENT 'Date of pregnancy registration with NHIS',
  `gravida` INT(2) DEFAULT NULL COMMENT 'Total number of pregnancies',
  `parity` INT(2) DEFAULT NULL COMMENT 'Number of previous deliveries',
  `gestational_age_weeks` INT(3) DEFAULT NULL COMMENT 'Gestational age in weeks at registration',
  `expected_delivery_date` DATE DEFAULT NULL COMMENT 'EDD',
  `antenatal_start_date` DATE DEFAULT NULL COMMENT 'Date first ANC visit',
  `health_facility_id` INT(11) DEFAULT NULL COMMENT 'Facility for ANC',
  `facility_other` VARCHAR(200) DEFAULT NULL COMMENT 'If facility not in list',
  `pregnancy_status` ENUM('Active','Delivered','Lost to Follow-up','Referred','Deceased','Other') NOT NULL DEFAULT 'Active',
  `delivery_date` DATE DEFAULT NULL,
  `delivery_outcome` VARCHAR(200) DEFAULT NULL,
  -- NHIS Processing Information
  `processing_date` DATE DEFAULT NULL COMMENT 'Date NHIS processed the exemption',
  `exemption_status` ENUM('Approved','Pending','Rejected','Under Review') NOT NULL DEFAULT 'Pending',
  `reference_number` VARCHAR(80) DEFAULT NULL COMMENT 'NHIS reference/transaction number',
  `processed_by` INT(11) DEFAULT NULL COMMENT 'User ID of staff who processed',
  `nhis_remarks` TEXT DEFAULT NULL COMMENT 'Remarks on NHIS processing',
  -- General
  `general_remarks` TEXT DEFAULT NULL,
  `created_by` INT(11) NOT NULL COMMENT 'User who created record',
  `updated_by` INT(11) DEFAULT NULL COMMENT 'User who last updated record',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_record_number` (`record_number`),
  UNIQUE KEY `uq_ghana_card` (`ghana_card_number`),
  KEY `idx_nhis_membership` (`nhis_membership_number`),
  KEY `idx_first_name` (`first_name`),
  KEY `idx_last_name` (`last_name`),
  KEY `idx_registration_date` (`registration_date`),
  KEY `idx_community` (`community_id`),
  KEY `idx_facility` (`health_facility_id`),
  KEY `idx_status` (`pregnancy_status`),
  KEY `idx_exemption_status` (`exemption_status`),
  KEY `fk_pw_community` (`community_id`),
  KEY `fk_pw_facility` (`health_facility_id`),
  KEY `fk_pw_processed_by` (`processed_by`),
  KEY `fk_pw_created_by` (`created_by`),
  CONSTRAINT `fk_pw_community` FOREIGN KEY (`community_id`) REFERENCES `communities` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_pw_facility` FOREIGN KEY (`health_facility_id`) REFERENCES `health_facilities` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_pw_processed_by` FOREIGN KEY (`processed_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_pw_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- TABLE: audit_logs
-- ============================================================
CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) DEFAULT NULL,
  `username` VARCHAR(80) DEFAULT NULL COMMENT 'Snapshot of username at time of action',
  `action` VARCHAR(100) NOT NULL,
  `module` VARCHAR(80) DEFAULT NULL,
  `record_id` INT(11) DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `user_agent` VARCHAR(300) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_audit_user` (`user_id`),
  KEY `idx_audit_action` (`action`),
  KEY `idx_audit_created` (`created_at`),
  CONSTRAINT `fk_audit_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- TABLE: system_settings
-- ============================================================
CREATE TABLE IF NOT EXISTS `system_settings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `setting_key` VARCHAR(100) NOT NULL,
  `setting_value` TEXT DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `updated_by` INT(11) DEFAULT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_setting_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `system_settings` (`setting_key`, `setting_value`, `description`) VALUES
('system_name', 'NHIS Pregnancy Exemption Registration System', 'Full system name'),
('system_short_name', 'NHIS-PERS', 'Short system name'),
('office_name', 'NHIS Twifo Praso District Office', 'Office name'),
('district', 'Twifo Atti-Morkwa', 'Default district'),
('region', 'Central Region', 'Default region'),
('record_prefix', 'NHIS-TP', 'Prefix for auto-generated record numbers'),
('records_per_page', '20', 'Number of records per page in tables'),
('session_timeout', '60', 'Session timeout in minutes'),
('allow_staff_delete', '0', 'Allow staff to delete records (0=No, 1=Yes)'),
('system_version', '1.0.0', 'Current system version'),
('footer_text', 'NHIS Twifo Praso District Office &mdash; Pregnancy Exemption Registration System', 'Footer text');

-- ============================================================
-- SAMPLE DATA: Pregnant Women Records
-- ============================================================
INSERT INTO `pregnant_women` (
  `record_number`, `nhis_membership_number`, `ghana_card_number`,
  `first_name`, `middle_name`, `last_name`,
  `sex`, `phone`, `community_id`, `district`, `region`,
  `date_of_birth`,
  `registration_date`, `gravida`, `parity`, `gestational_age_weeks`, `expected_delivery_date`,
  `antenatal_start_date`, `health_facility_id`, `pregnancy_status`,
  `processing_date`, `exemption_status`, `reference_number`, `processed_by`,
  `nhis_remarks`, `created_by`, `created_at`
) VALUES
('NHIS-TP-2024-00001','12345678',NULL,
 'Akosua','','Amponsah','Female','0244001001',1,'Twifo Atti-Morkwa','Central Region','1998-04-15',
 '2024-01-08',2,1,16,'2024-07-10','2024-01-08',1,'Active',
 '2024-01-08','Approved','NHIS/TP/2024/0001',2,'Exemption granted',2,'2024-01-08 09:30:00'),

('NHIS-TP-2024-00002',NULL,'GHA-234567890-2',
 'Ama','','Yeboah','Female','0201002002',2,'Twifo Atti-Morkwa','Central Region','2000-11-20',
 '2024-01-15',1,0,10,'2024-08-20','2024-01-15',2,'Active',
 '2024-01-15','Approved','NHIS/TP/2024/0002',2,'First pregnancy exemption approved',2,'2024-01-15 10:00:00'),

('NHIS-TP-2024-00003','34567890',NULL,
 'Efua','Ama','Asante','Female','0277003003',3,'Twifo Atti-Morkwa','Central Region','1995-07-30',
 '2024-01-22',3,2,22,'2024-06-15','2024-01-22',3,'Active',
 '2024-01-22','Approved','NHIS/TP/2024/0003',3,'',2,'2024-01-22 11:15:00'),

('NHIS-TP-2024-00004',NULL,'GHA-456789012-4',
 'Adjoa','','Boateng','Female','0242004004',4,'Twifo Atti-Morkwa','Central Region','2002-03-05',
 '2024-02-05',1,0,8,'2024-09-01','2024-02-05',4,'Active',
 '2024-02-05','Pending',NULL,3,'Awaiting additional documentation',2,'2024-02-05 08:45:00'),

('NHIS-TP-2024-00005','56789012',NULL,
 'Abena','Yaa','Owusu','Female','0244005005',1,'Twifo Atti-Morkwa','Central Region','1993-09-18',
 '2024-02-12',4,3,28,'2024-05-28','2024-02-12',1,'Delivered',
 '2024-02-12','Approved','NHIS/TP/2024/0005',2,'Delivered successfully',2,'2024-02-12 14:00:00'),

('NHIS-TP-2024-00006',NULL,'GHA-678901234-6',
 'Yaa','','Darkwah','Female','0201006006',7,'Twifo Atti-Morkwa','Central Region','1997-06-22',
 '2024-02-20',2,1,14,'2024-08-05','2024-02-20',6,'Active',
 '2024-02-20','Approved','NHIS/TP/2024/0006',3,'',3,'2024-02-20 09:00:00'),

('NHIS-TP-2024-00007','78901234',NULL,
 'Akua','Serwaa','Mensah','Female','0244007007',8,'Twifo Atti-Morkwa','Central Region','2001-01-10',
 '2024-03-01',1,0,6,'2024-09-20','2024-03-01',7,'Active',
 '2024-03-01','Pending',NULL,2,'',2,'2024-03-01 10:30:00'),

('NHIS-TP-2024-00008',NULL,'GHA-890123456-8',
 'Maame','','Serwaa','Female','0277008008',9,'Twifo Atti-Morkwa','Central Region','1999-12-25',
 '2024-03-10',2,1,20,'2024-07-25','2024-03-10',1,'Active',
 '2024-03-10','Approved','NHIS/TP/2024/0008',3,'',3,'2024-03-10 13:00:00'),

('NHIS-TP-2024-00009','90123456',NULL,
 'Esi','Manu','Appiah','Female','0244009009',10,'Twifo Atti-Morkwa','Central Region','1996-08-14',
 '2024-03-18',3,2,32,'2024-05-10','2024-03-18',2,'Delivered',
 '2024-03-18','Approved','NHIS/TP/2024/0009',2,'Delivered. Baby healthy',2,'2024-03-18 09:15:00'),

('NHIS-TP-2024-00010',NULL,'GHA-012345678-0',
 'Adwoa','','Frimpong','Female','0201010010',1,'Twifo Atti-Morkwa','Central Region','2003-05-07',
 '2024-04-02',1,0,12,'2024-10-05','2024-04-02',1,'Active',
 '2024-04-02','Approved','NHIS/TP/2024/0010',2,'',2,'2024-04-02 11:00:00'),

('NHIS-TP-2024-00011','11111111',NULL,
 'Akosua','Ama','Tawiah','Female','0242011011',2,'Twifo Atti-Morkwa','Central Region','1994-02-28',
 '2024-04-15',5,4,18,'2024-09-10','2024-04-15',2,'Active',
 '2024-04-15','Approved','NHIS/TP/2024/0011',3,'High parity; referred for specialist care',3,'2024-04-15 14:30:00'),

('NHIS-TP-2024-00012',NULL,'GHA-222222222-2',
 'Ama','','Bonsu','Female','0244012012',3,'Twifo Atti-Morkwa','Central Region','2000-07-16',
 '2024-05-03',2,1,24,'2024-08-20','2024-05-03',3,'Active',
 '2024-05-03','Approved','NHIS/TP/2024/0012',2,'',2,'2024-05-03 10:00:00'),

('NHIS-TP-2024-00013','33333333',NULL,
 'Efua','Kuma','Kumi','Female','0277013013',1,'Twifo Atti-Morkwa','Central Region','1998-10-11',
 '2024-05-20',1,0,8,'2024-12-10','2024-05-20',1,'Active',
 '2024-05-20','Under Review',NULL,3,'Membership verification pending',3,'2024-05-20 09:30:00'),

('NHIS-TP-2024-00014',NULL,'GHA-444444444-4',
 'Yaa','Serwaah','Asante','Female','0244014014',4,'Twifo Atti-Morkwa','Central Region','1991-04-20',
 '2024-06-07',6,5,36,'2024-07-05','2024-06-07',4,'Delivered',
 '2024-06-07','Approved','NHIS/TP/2024/0014',2,'Delivered; record complete',2,'2024-06-07 08:00:00'),

('NHIS-TP-2024-00015','55555555',NULL,
 'Abena','','Poku','Female','0201015015',7,'Twifo Atti-Morkwa','Central Region','2002-09-03',
 '2024-06-15',1,0,10,'2024-12-20','2024-06-15',6,'Active',
 '2024-06-15','Approved','NHIS/TP/2024/0015',3,'',3,'2024-06-15 11:00:00');

-- ============================================================
-- Sample Audit Log Entries
-- ============================================================
INSERT INTO `audit_logs` (`user_id`, `username`, `action`, `module`, `record_id`, `description`, `ip_address`) VALUES
(1, 'admin', 'LOGIN', 'Auth', NULL, 'Administrator logged in', '127.0.0.1'),
(2, 'abena.mensah', 'LOGIN', 'Auth', NULL, 'Staff logged in', '127.0.0.1'),
(2, 'abena.mensah', 'CREATE_RECORD', 'Pregnancy', 1, 'New pregnancy registration created: NHIS-TP-2024-00001', '127.0.0.1'),
(2, 'abena.mensah', 'CREATE_RECORD', 'Pregnancy', 2, 'New pregnancy registration created: NHIS-TP-2024-00002', '127.0.0.1'),
(3, 'kofi.agyemang', 'LOGIN', 'Auth', NULL, 'Staff logged in', '127.0.0.1'),
(3, 'kofi.agyemang', 'CREATE_RECORD', 'Pregnancy', 6, 'New pregnancy registration created: NHIS-TP-2024-00006', '127.0.0.1'),
(1, 'admin', 'CREATE_USER', 'Users', 2, 'Created user account: abena.mensah', '127.0.0.1'),
(1, 'admin', 'CREATE_USER', 'Users', 3, 'Created user account: kofi.agyemang', '127.0.0.1');

COMMIT;
